# syntax=docker/dockerfile:1

FROM golang:1.19-alpine
WORKDIR /test
COPY go.* .
RUN go mod download
COPY ./test/integration ./integration
CMD CGO_ENABLED=0 go test -tags integration -v ./integration/...