# syntax=docker/dockerfile:1

FROM golang:1.24-alpine
WORKDIR /test
COPY go.* ./
RUN go mod download
COPY ./test ./test
ENV CGO_ENABLED=0
CMD go test -tags integration -v ./test/acceptance/... && \
    go test -tags integration -v ./test/faultinjection/...